const APP_CONFIG = Object.freeze({
  name: "Massa horària",
  subtitle: "Escola Ramon Pont",
  version: "0.5.0",
  accessPasscode: "SoL",
  accessCacheSeconds: 21600,
  spreadsheetProperty: "DATABASE_SPREADSHEET_ID",
  allowedRoles: Object.freeze(["ADMIN", "EDITOR", "LECTOR"]),
  editableRoles: Object.freeze(["ADMIN", "EDITOR"]),
  adminRoles: Object.freeze(["ADMIN"]),
  assignmentTypes: Object.freeze({
    CLASSE: { label: "Classe", coverageFactor: 1 },
    REFORC: { label: "Reforç", coverageFactor: 0 },
    DESDOBLAMENT: { label: "Desdoblament", coverageFactor: 0.5 },
    COMPLEMENTARIA: { label: "Complementària", coverageFactor: 1 },
  }),
});

const TABLES = Object.freeze({
  Configuracio: ["Clau", "Valor"],
  CursosEscolars: ["Id", "Nom", "Estat", "Actiu", "CreatEl"],
  Professorat: ["Id", "Cognom1", "Cognom2", "Nom", "NomComplet", "Actiu"],
  Contractes: ["Id", "CursEscolarId", "ProfessorId", "Hores", "Actiu"],
  Grups: ["Id", "CursEscolarId", "Codi", "Nom", "Etapa", "Ordre", "HoresObjectiu", "Actiu"],
  Materies: ["Id", "Nom", "NomCurt", "Activa"],
  PlaEstudis: [
    "Id",
    "CursEscolarId",
    "GrupId",
    "MateriaId",
    "Ordre",
    "HoresObjectiu",
    "TipusBase",
    "Actiu",
  ],
  Assignacions: [
    "Id",
    "CursEscolarId",
    "GrupId",
    "MateriaId",
    "ProfessorId",
    "Tipus",
    "Hores",
    "FactorCobertura",
    "Observacions",
    "Activa",
    "ActualitzatEl",
    "ActualitzatPer",
  ],
  Carrecs: ["Id", "Nom", "Ordre", "Actiu"],
  AssignacionsCarrecs: [
    "Id",
    "CursEscolarId",
    "ProfessorId",
    "CarrecId",
    "Hores",
    "Observacions",
    "Activa",
    "ActualitzatEl",
    "ActualitzatPer",
  ],
  ReglesComput: ["Id", "CursEscolarId", "Etapa", "PercentatgeHdc", "Actiu"],
  Usuaris: ["Email", "Nom", "Rol", "Actiu"],
  RegistreCanvis: [
    "DataHora",
    "Usuari",
    "Accio",
    "Entitat",
    "RegistreId",
    "Abans",
    "Despres",
  ],
});
